- name: Cambio de contrasena
  hosts: elastic-log-cluster
  become: true
  tasks:
    - name: Cambio de contrasena
      expect:
        command: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -i -u kibana_system"
        responses:
          '.*Please confirm that you would like to continue \[y/N\].*': "y"
          'Enter password for \[kibana_system\]: ': "kibana_adp_terraform2023"
          'Re-enter password for \[kibana_system\]: ': "kibana_adp_terraform2023"
        echo: yes


