- name: Reemplazar y Descomentar variables en el archivo de configuración de Elasticsearch nodo secundario
  hosts: sec-elastic-log
  become: yes

  tasks:
    - name: Descomentar y reemplazar cluster.name en la configuración de Elasticsearch
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#(.*cluster\.name: )my-application$'
        replace: '\g<1>elastic-log-cluster'

    - name: Descomentar y reemplazar http.port en la configuración de Elasticsearch
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#(.*http\.port: )9200$'
        replace: '\g<1>9200'

    - name: Descomentar y reemplazar node.name en la configuración de Elasticsearch
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#(.*node\.name: )node-1$'
        replace: '\g<1>sec-elastic-log'

    - name: Descomentar y reemplazar network.host en la configuración de Elasticsearch
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#(.*network\.host: )192\.168\.0\.1$'
        replace: '\g<1>"sec-elastic-log"'

    - name: Descomentar y reemplazar discovery.seed_hosts en la configuración de Elasticsearch
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#(.*discovery\.seed_hosts: )\["host1", "host2"\]$'
        replace: '\g<1>["10.194.0.20"]'

    - name: Reemplazar cluster.initial_master_nodes 
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^(.*cluster\.initial_master_nodes: )\["sec-elastic-log"\]$'
        replace: '\g<1>["prim-elastic-log"]'

    - name: Reemplazar keystore a una variable temporal
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^(\s*keystore\.path: )certs/transport\.p12$'
        replace: '\g<1>certs/temporal.p12'

    - name: Reemplazar keystore
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^(\s*keystore\.path: )certs/transport\.p12$'
        replace: '\g<1>certs/elastic-certificates.p12'

    - name: Cambiar variable temporal keystore
      replace:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^(\s*keystore\.path: )certs/temporal\.p12$'
        replace: '\g<1>certs/elastic-certificates.p12'

    - name: Reemplazar truststore
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^(\s*)truststore.path:'
        line: '  truststore.path: certs/elastic-certificates.p12'
        firstmatch: yes
