- name: Guardar contrasenas en keystore y truststore
  hosts: elastic-log-cluster
  become: true
  tasks:
    - name: Guardar contraseña en keystore
      expect:
        command: "/usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password"
        responses:
          'Setting xpack.security.http.ssl.keystore.secure_password already exists. Overwrite\? \[y/N\]': "y\n"
          'Enter value for xpack.security.http.ssl.keystore.secure_password:': "clientes_adp_terraform2023\n"
          'Enter password for elastic-certificates.p12 :': "clientes_adp_terraform2023\n"
        chdir: "/usr/share/elasticsearch/bin/"

