- name: Guardar contrasenas en keystore y truststore
  hosts: prim-elastic-log
  become: true
  tasks:
    - name: Guardar contraseña en keystore
      expect:
        command: "/usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password"
        responses:
          'Setting xpack.security.transport.ssl.keystore.secure_password already exists. Overwrite\? \[y/N\]': "y\n"
          'Enter value for xpack.security.transport.ssl.keystore.secure_password:': "elastic_adp_terraform2023\n"
          'Enter password for elastic-certificates.p12 :': "elastic_adp_terraform2023\n"
        chdir: "/usr/share/elasticsearch/bin/"

    - name: Guardar contraseña en truststore
      expect:
        command: "/usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password"
        responses:
          'Setting xpack.security.transport.ssl.truststore.secure_password already exists. Overwrite\? \[y/N\]': "y\n"
          'Enter value for xpack.security.transport.ssl.truststore.secure_password:': "elastic_adp_terraform2023\n"
        chdir: "/usr/share/elasticsearch/bin/"
