- hosts: prim-elastic-log
  gather_facts: false

  tasks:
    - name: Fetch file from prim-elastic-log to Ansible Controller
      fetch:
        src: /home/adp_terraform2023/pintado.txt
        dest: /home/Proyecto/conf_ansible/testeo_transferencia/
        flat: yes
      
      vars:
        ansible_ssh_private_key_file: /root/.ssh/llave_ssh_proyecto

- hosts: sec-elastic-log
  gather_facts: false

  tasks:
    - name: Transfer file from Ansible Controller to sec-elastic-log
      synchronize:
        src: /home/Proyecto/conf_ansible/testeo_transferencia/pintado.txt
        dest: /home/adp_terraform2023/
      
